---
- name: Update homebrew and all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install homebrew packages
  homebrew:
    name: "{{brew_packages}}"

- name: Remove old homebrew packages
  homebrew:
    name: "{{old_brew_packages}}"
    state: absent
    install_options: force

- name: Install homebrew casks
  homebrew_cask:
    name: "{{brew_casks}}"
    state: present
    install_options: force

- name: Provide alias to composer so we can run .phar
  file:
    src: /usr/local/bin/composer
    dest: /usr/local/bin/composer.phar
    state: link

- name: Cleanup any old brew packages not in use
  shell: brew cleanup
