---
- name: Update homebrew and all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install homebrew taps
  homebrew_tap:
    name: "{{brew_taps}}"
    state: present

- name: Install homebrew packages
  homebrew:
    name: "{{brew_packages}}"

- name: Remove old homebrew packages
  homebrew:
    name: "{{old_brew_packages}}"
    state: absent
    install_options: force

- name: Install homebrew casks
  homebrew_cask:
    name: "{{brew_casks}}"
    state: present
    install_options: force

- name: Remove old homebrew casks
  homebrew_cask:
    name: "{{old_brew_casks}}"
    state: absent
    install_options: force

- name: Cleanup any old brew packages not in use
  shell: brew cleanup
