---
- name: Install PHP
  homebrew:
    name: "php{{ php_formula_name }}"
    state: latest

- name: Install PHP Xdebug extension
  pear:
    name: pecl/xdebug
    state: latest

- name: Copy php.ini file
  copy:
    src: custom-php.ini
    dest: /usr/local/etc/php/{{ php_version }}/conf.d/
    mode: "644"
