---
brew_packages:
  - ansible
  - aws-sam-cli
  - awscli
  - cowsay
  - curl
  - fzf
  - git
  - github/gh/gh
  - go
  - htop
  - httpie
  - hugo
  - jq
  - nmap
  - node
  - reattach-to-user-namespace
  - shellcheck
  - terraform
  - tflint
  - tmux
  - tmuxinator
  - wget

old_brew_packages:
  - bash-completion
  - fx
  - hub
  - pyinvoke
  - cfn-lint

brew_taps:
  - aws/tap

brew_casks:
  - vagrant
  - virtualbox
  - postman

old_brew_casks:
  - dotnet-sdk

node_packages:
  - cdk
  - gulp-cli
  - http-server
  - less
  - lighthouse
  - pa11y
  - pa11y-ci
  - underscore-cli

old_node_packages:
  - grunt-cli
